name: Test and build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ${{ "{{" }}matrix.os{{ "}}" }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
{%- if cookiecutter.use_windows_ci_runner %}
          - windows-latest
{%- endif %}
{%- if cookiecutter.use_macos_ci_runner %}
          - macos-latest
{%- endif %}
        python-version: ['3.14']

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          prune-cache: false
          activate-environment: true
          python-version: ${{ "{{" }} matrix.python-version {{ "}}" }}

      - name: Install dependencies
        run: uv sync

      - name: Run mypy
        run: mypy .

      - name: Run tests
        run: pytest
{%- if cookiecutter.mkdocs %}

      - name: Install doc dependencies
        run: uv sync --group doc

      - name: Check that documentation builds cleanly with MkDocs
        if: matrix.os == 'ubuntu-latest'
        run: mkdocs build --strict
{%- endif %}
